project:
  type: website
  output-dir: docs

website:
  title: "Behrokh Clustering code"
  repo-url: https://github.com/behrokhb/clusterbb
  repo-actions: [edit, issue]
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/behrokhb/clusterbb
     
format:
  html:
    theme: quartz
    css: styles.css
