---
title: "Behrokh_Blog_R.Code"
format: html
editor: visual
By: Behrokh Bazmara
---


```{r}
                               # Clustering

#Importing required libararies
install.packages("FactoMineR")
install.packages("factoextra")
library(cluster)
library(parameters)

#Read in data
FitData2<-read.csv('Book3.csv') 

#Scaling data
FitData2 <- scale(FitData2)

#View in data (to show only the first 6 obs)
head(FitData2)

#Elbow Method (Number of clusters)
k.max <- 10
wss <- sapply(2:k.max, function(k){kmeans(FitData2,k, nstart=10)$tot.withinss})
print(wss)
plot(2:k.max, wss, type="b", pch=16, xlab="Number of Cluster K", 
ylab="Total within cluster sum of squares")

#Finding optimal clusters to the training
kmeans <- kmeans(FitData2, centers=4, nstart = 10)
kmeans
100*kmeans$betweenss / kmeans$totss

#cluster identification
kmeans$cluster

# #Visualizing clusters 
clusplot(FitData2[,6:7],
         kmeans$cluster,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste("Cluster of data"),
         xlab = '',
         ylab = '')
legend("topleft", legend=c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4"), col = c("blue", "red", "purple","green"), lty= 1:2, cex = 0.8)
```
In my R code, I employed the elbow method to determine the optimal number of clusters for a clustering analysis on a crash data set.
The data set included crucial features such as roadway "lane_count" and "mix type", which are essential factors in understanding the characteristics of different road segments concerning safety.
The first step involved selecting and possibly standardizing these features to ensure uniform contributions to the clustering process.
Subsequently, I applied the k-means clustering algorithm across a range of cluster numbers (k) and calculated the sum of squared distances within clusters (WSS) for each configuration. The elbow method involves plotting the number of clusters against the corresponding WSS and visually or programmatically identifying the "elbow" point, which signifies the optimal k where additional clusters cease to significantly improve the clustering performance.
This data-driven approach allowed me to discern the natural structure within the crash data set based on lane_count and mix type, providing valuable insights into potential groupings of roadway segments with distinct safety characteristics.
